name: Everything works
on: [push, pull_request]

jobs:
  Remod:
    runs-on: windows-latest
    env:
      GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
    steps:
      - name: Checking repo
        uses: actions/checkout@v2
        with:
          fetch-depth: 2

      - name: Installing dependencies
        run: yarn install

      - name: Run Jest
        run: yarn test
